version: '3.4'

services:
  kubeui:
    image: "powersvr:5000/kubeui"     
    build:
      context: .
      dockerfile: KubeUI/Dockerfile
    ports:
      - 4002:80

  kubeapi:
    image: "powersvr:5000/kubeapi"    
    build:
      context: .
      dockerfile: kubeApi/Dockerfile
    ports:
      - 4001:80
